<?php
/**
 * Created by PhpStorm.
 * User: TuanPV
 * Date: 6/27/2017
 * Time: 8:25 PM
 */

namespace frontend\widgets;
use common\models\Category;
use common\models\Info;
use common\models\News;
use yii\base\Widget;
use Yii;

class ExperienceWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('experience');
    }
}