<?php
/**
 * Created by PhpStorm.
 * User: TuanPV
 * Date: 6/27/2017
 * Time: 8:25 PM
 */

namespace frontend\widgets;
use common\models\Category;
use common\models\Info;
use common\models\News;
use yii\base\Widget;
use Yii;

class FindPartner extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $therePosts = News::find()
            ->select('id,image_slide,title,description')
            ->andWhere(['status' => News::STATUS_ACTIVE])
            ->andWhere(['type' => News::TYPE_PARTNER])
            ->limit(3)
            ->all();
        return $this->render('find-partner',[
            'therePosts'=>$therePosts,
        ]);
    }
}