<?php
/**
 * Created by PhpStorm.
 * User: TuanPV
 * Date: 6/27/2017
 * Time: 8:25 PM
 */

namespace frontend\widgets;
use common\models\Category;
use common\models\HomeSolution;
use common\models\Info;
use yii\base\Widget;
use Yii;

class HeaderWidget extends Widget
{
    public $category;
    public $parentCategory;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $this->parentCategory = Category::find()->andWhere(['status'=>Category::STATUS_ACTIVE])->andWhere('parent_id is null')->all();
        $info = Info::findOne(Info::ID);
        return $this->render('header',[
            'listCategory'=>$this->parentCategory,
            'info'=>$info,
        ]);
    }
}