<?php
/**
 * Created by PhpStorm.
 * User: TuanPV
 * Date: 6/27/2017
 * Time: 8:25 PM
 */

namespace frontend\widgets;
use common\models\Category;
use yii\base\Widget;
use Yii;

class MenuWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $listCat = Category::find()
            ->andWhere(['status'=>Category::STATUS_ACTIVE])
            ->all();
        return $this->render('menu-right',[
            'listCat' => $listCat,
        ]);
    }
}