<?php
/**
 * Created by PhpStorm.
 * User: TuanPV
 * Date: 6/27/2017
 * Time: 8:25 PM
 */

namespace frontend\widgets;
use common\models\Category;
use common\models\Info;
use common\models\News;
use yii\base\Widget;
use Yii;

class SlideWidget extends Widget
{
    public $message;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $listSlide = News::find()
            ->select('id,image_slide,title,description')
            ->andWhere(['status' => News::STATUS_ACTIVE])
            ->andWhere(['is_slide' => News::IS_SLIDE])->all();
        $info = Info::findOne(Info::ID);
        return $this->render('slide',[
            'listSlide'=>$listSlide,
            'info' => $info
        ]);
    }
}